#!/usr/bin/env bash
set -euo pipefail

PORT="${PORT:-8000}"
SLOT_LABEL="${SLOT_LABEL:-qwen235}"
DOCKER_IMAGE="${DOCKER_IMAGE:-nvcr.io/nvidia/tensorrt-llm/release:1.0.0rc3}"
MAX_NUM_TOKENS="${MAX_NUM_TOKENS:-32768}"
MAX_BATCH_SIZE="${MAX_BATCH_SIZE:-1}"
FREE_GPU_MEMORY_FRACTION="${FREE_GPU_MEMORY_FRACTION:-0.9}"
STARTUP_RETRIES="${STARTUP_RETRIES:-3}"
API_READY_TIMEOUT_SECS="${API_READY_TIMEOUT_SECS:-1200}"
RETRY_BACKOFF_SECS="${RETRY_BACKOFF_SECS:-20}"
MODEL_SPEC="${MODEL_SPEC:-/mnt/models/nvidia/Qwen3-235B-A22B-NVFP4/files}"

export PORT SLOT_LABEL DOCKER_IMAGE MAX_NUM_TOKENS MAX_BATCH_SIZE FREE_GPU_MEMORY_FRACTION STARTUP_RETRIES API_READY_TIMEOUT_SECS RETRY_BACKOFF_SECS MODEL_SPEC
exec /home/admin/apps/LLMCommune/scripts/run_dual_spark_trtllm_common.sh
